### ISSUE TITLE
Off-by-one in webgl-tilemap

### ISSUE THREAD

**Issue by yyny** [toji/webgl-samples#3]
Hi, I'm writing my own tile map implementation based on yours, and it seems your implementation has an off-by-one on [line 70](https://github.com/toji/webgl-samples/blob/21ea237b2fa200a891305b4db0e83b63548f09d5/js/webgl-tilemap.js#L70).

The intention of this line seems to be to convert the normalized floats in `tile.xy` back to the range of an unsigned byte, but that range is `0` to `255`, not to `256`. I made the same mistake, I kept getting weird striped patterns when scaling.

**Comment by toji** [comment]
Thanks! Good catch!

**Comment by mreinstein** [comment]
@yyny  did you ever get the scaling to work?   I'm doing the same thing and running into tile edge bleeding at non-integer tile scales.

**Comment by mreinstein** [comment]
<img width="306" alt="Screenshot 2023-03-28 at 12 18 04 PM" src="https://user-images.githubusercontent.com/718067/228373676-af283c18-434e-4c10-8ae6-e2e60cfcfa28.png">
